version: "3.8"

services:
  monitoro:
    container_name: monitoro-container # Nome do container
    image: monitoro-image # Nome da imagem
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped # Reinicia o container a menos que seja parado manualmente
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limita o uso de CPU a 50% de um núcleo
          memory: "256M" # Limita o uso de memória a 512 MB
